# This setup uses an unicorn config similar to default one but suitable for use with Dokku,
# it can be found at deployment/chattermill/unicorn.rb

# Also, this setup uses the old Procfile structure with separate processes
# so we can use Sidekiq and keep DelayedJob for schedule.
web: bundle exec unicorn -p $PORT -c ./deployment/chattermill/unicorn.rb
schedule: bundle exec rails runner bin/schedule.rb
sidekiq: bundle exec sidekiq -C config/sidekiq.yml

# Uncommnet next line to enable twitter stream if needed
# twitter: bundle exec rails runner bin/twitter_stream.rb
