apiVersion: v2
name: huginn
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
- name: mariadb
  version: "7.3.16"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mariadb.enabled
