web: sudo bundle exec unicorn_rails -c config/unicorn.rb -E production
schedule: sudo RAILS_ENV=production bundle exec rails runner bin/schedule.rb
twitter: sudo RAILS_ENV=production bundle exec rails runner bin/twitter_stream.rb
dj: sudo RAILS_ENV=production bundle exec script/delayed_job run
