#!/bin/bash
set -e

cd /app

# Cleanup any leftover pid file
if [ -f /app/tmp/pids/server.pid ]; then
  rm /app/tmp/pids/server.pid
fi

source /scripts/setup_env

# Fix up the Procfile.
if [ -n "${DO_NOT_RUN_JOBS}" ]; then
  sed -i -e 's/^jobs:/#jobs:/' /app/Procfile
fi

# start supervisord
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
