[program:smokescreen]
command=/scripts/smokescreen
priority=5
directory=/app
process_name=%(program_name)s
autostart=false
autorestart=true
stdout_events_enabled=true
stderr_events_enabled=true
stopsignal=TERM
startsecs=1
stopwaitsecs=5
