# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.omnibus.chef_version = :latest

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "roles"
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
    chef.add_role("huginn_development")
    # chef.add_role("huginn_production")
  end

  config.vm.provider :virtualbox do |vb, override|
    #vb.memory = 1024
    #vb.cpus = 4
    override.vm.box = "hashicorp/precise64"
    override.vm.network :forwarded_port, host: 3000, guest: 3000
  end

  config.vm.provider :parallels do |prl, override|
    override.vm.box = "parallels/ubuntu-12.04"
  end
end
