# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.omnibus.chef_version = :latest

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "roles"
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
    chef.add_role("huginn_development")
    # chef.add_role("huginn_production")
  end

  config.vm.provider :virtualbox do |vb, override|
    override.vm.box = "hashicorp/precise64"
    override.vm.network :forwarded_port, host: 3000, guest: 3000
  end

  config.vm.provider :parallels do |prl, override|
    override.vm.box = "parallels/ubuntu-12.04"
  end

  config.vm.provider :aws do |aws, override| 
    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    aws.access_key_id = ""
    aws.secret_access_key = ""
    aws.keypair_name = ""
    aws.region = "us-east-1"
    aws.ami = "ami-d0f89fb9"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ""
  end
end
