name             "huginn"
maintainer       "CloCkWeRX"
maintainer_email "daniel.oconnor@gmail.com"
license          "BSD"
description      "Installs Huginn"
long_description "Installs Huginn"
version          "0.0.1"
depends          "ruby_build"
depends          "rbenv"
