postgresdata:
  image: postgres
  command: /bin/true

postgres:
  image: postgres
  volumes_from:
    - postgresdata
  environment:
    POSTGRES_PASSWORD: myhuginnpassword
    POSTGRES_USER: huginn

huginn_web:
  build: .
  restart: always
  extends:
    file: environment.yml
    service: huginn_base
  environment:
    DATABASE_ADAPTER: postgresql
  ports:
    - 3000:3000
  links:
    - postgres

huginn_threaded:
  build: .
  restart: always
  extends:
    file: environment.yml
    service: huginn_base
  environment:
    DATABASE_ADAPTER: postgresql
  links:
    - postgres
  command: /scripts/init bin/threaded.rb

# huginn_schedule:
#   build: .
#   extends:
#     file: environment.yml
#     service: huginn_base
#   environment:
#     DATABASE_ADAPTER: postgresql
#   links:
#     - postgres
#   command: /scripts/init bin/schedule.rb


# huginn_twitter_stream:
#   build: .
#   extends:
#     file: environment.yml
#     service: huginn_base
#   environment:
#     DATABASE_ADAPTER: postgresql
#   links:
#     - postgres
#   command: /scripts/init bin/twitter_stream.rb


# huginn_dj1:
#   build: .
#   extends:
#     file: environment.yml
#     service: huginn_base
#   environment:
#     DATABASE_ADAPTER: postgresql
#   links:
#     - postgres
#   command: /scripts/init script/delayed_job run

